spring.application.name=Learning


# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase

# Database Username
spring.datasource.username=postgres

# Database Password
spring.datasource.password=6120

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries
spring.jpa.show-sql=true

# Format SQL Queries
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect (optional in newer Spring Boot versions)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Optional)
server.port=8080